= Disaster recovery

This page explains how to recover from a situation in which:

- your server has failed, and needs to be restored from backups;
- a CDC client application was running and processing changes when the server failed, and it may have missed some changes triggered by committed transactions before the server became unavailable.

The rest of the page covers the prerequisites that your setup must fulfill for you to be able to recover from a disaster, and the steps you need to take to recover.
Use this page both to set yourself up to be prepared to face disasters, and to recover from them should they occurr.

[WARNING]
====
The recovery procedure works both on single instances and on clusters since Neo4j 2024.04.
It does not work on clusters running versions earlier than 2024.04.

The exact constraint for clusters is that the recovery should happen onto a cluster running Neo4j 2024.04 or later, and the differential backups _after aggregation_ come from Neo4j 2024.04 or later.
Earlier backups in the chain could have been exported under earlier versions. (CONFIRM)
====


== Setup prerequisites

- You have link:https://neo4j.com/docs/operations-manual/current/backup-restore/online-backup/#online-backup-example[incremental backups] of the failed database. For example, you could have a scheduled job that takes a backup every hour.
- The xref:get-started/self-managed.adoc#log-retention[transaction log retention period] is smaller than the interval between backups.
- The database to restore was running with xref:get-started/self-managed.adoc[`txLogEnrichment`] set to either `FULL` or `DIFF`.
- You keep track of the change event that your CDC application has processed last (specifically, the event ID and the field `txCommitTime`).


== Recovery steps

To be able to recover from a disaster, you need database backups and the information on the CDC event that was last processed.
As a concrete example for the recovery procedure, suppose the backup directory contains the following files:

.Backup directory
[source,shell]
----
root@737154f61ca4:/var/lib/neo4j# ls -l backups/neo4j/
-rw-r--r-- 1 root root 37155 Apr 18 06:36 neo4j-2025-04-18T06-36-12.backup
-rw-r--r-- 1 root root  1291 Apr 18 06:56 neo4j-2025-04-18T06-56-36.backup
-rw-r--r-- 1 root root  1012 Apr 18 06:57 neo4j-2025-04-18T06-57-21.backup
-rw-r--r-- 1 root root  1185 Apr 18 06:57 neo4j-2025-04-18T06-57-30.backup
-rw-r--r-- 1 root root  1704 Apr 18 06:59 neo4j-2025-04-18T06-59-12.backup
-rw-r--r-- 1 root root  1688 Apr 18 06:59 neo4j-2025-04-18T06-59-41.backup
-rw-r--r-- 1 root root  1680 Apr 18 06:59 neo4j-2025-04-18T06-59-52.backup
----

and that the latest processed change event has ID `EWcd7MhuWPmkAAAAAAAACM9\__________wAAAZZHsCvl` and a `txCommitTime` of `2025-04-18T06:57:30.055000000Z`.


=== Stop CDC application

You are going to recreate the database and import the backups into it, so your CDC application should not be processing changes until the database is ready.
Stop it until it's time.


=== Aggregate backups

[NOTE]
This step is optional, but is also recommended out of disaster situations, to keep the size and number of backup files under control.

To reduce the time it takes to restore the backup, you can link:https://neo4j.com/docs/operations-manual/current/backup-restore/aggregate/[aggregate] together a number of incremental backup files.
Aggregate backup files up until the latest date _before_ the latest CDC `txCommitTime` processed event.

In the example situation, we can aggregate backups until `2025-04-18T06:57:30`. Because the backup files lack microsecond precisions, we aggregate until the previous file (`2025-04-18T06-57-21`) to be on the safe side.

.Backup aggregation
[source,shell]
----
root@737154f61ca4:/var/lib/neo4j# neo4j-admin backup aggregate --from-path=backups/neo4j/neo4j-2025-04-18T06-57-21.backup
Successfully aggregated backup chain of database 'neo4j', new artifact: '/var/lib/neo4j/backups/neo4j/neo4j-2025-04-18T07-08-09.backup'.
----

.Backup directory after aggregation
[source,shell]
----
root@737154f61ca4:/var/lib/neo4j# ls -l backups/neo4j/
-rw-r--r-- 1 root root  1185 Apr 18 06:57 neo4j-2025-04-18T06-57-30.backup
-rw-r--r-- 1 root root  1704 Apr 18 06:59 neo4j-2025-04-18T06-59-12.backup
-rw-r--r-- 1 root root  1688 Apr 18 06:59 neo4j-2025-04-18T06-59-41.backup
-rw-r--r-- 1 root root  1680 Apr 18 06:59 neo4j-2025-04-18T06-59-52.backup
-rw-r--r-- 1 root root 38769 Apr 18 07:08 neo4j-2025-04-18T07-08-09.backup
----


=== Recreate the database and restore backup

You can recreate the database and import the aggregated backup with a single `CREATE DATABASE` call, using the backup as seed.

[source,cypher]
----
CREATE DATABASE neo4j
OPTIONS {
    txLogEnrichment: 'DIFF',  // <.>
    seedURI: 'file:/var/lib/neo4j/backups/neo4j/neo4j-2025-04-18T07-08-09.backup'  // <.>
}
----

<.> The new database should have the same xref:get-started/self-managed.adoc[transaction log enrichment mode] as the backupped database.
<.> File stored in remote cloud buckets can be accessed without further configuration, whereas `file`, `http(s?)`, and `ftp` require configuration. For more information, see link:https://neo4j.com/docs/operations-manual/current/database-administration/standard-databases/seed-from-uri/#neo4j-seed-providers[Seed providers in Neo4j].


=== Restore incremental backups and restart CDC application

Once the database is running and it contains data until _before_ the latest CDC processed event, you can:

1. restore the next (incremental) backup file in the chain;
2. xref:procedures/index.adoc#query[query for changes] from the latest processed event ID;
3. repeat the previous steps until you run out of backup files.

In the example, the first un-restored backup is `neo4j-2025-04-18T06-57-30.backup`, so we start by restoring that.
We can then query for CDC changes happened after the event ID we recorded before the database went offline.

[source,shell]
----
neo4j-admin database restore --from-path=backups/neo4j/neo4j-2025-04-18T06-57-30.backup --restore-until="2025-04-18 06:57:30" neo4j
----

[source,cypher]
----
CALL db.cdc.query('EWcd7MhuWPmkAAAAAAAACM9__________wAAAZZHsCvl') YIELD id, event, metadata
RETURN id, event, metadata
----

After restoring each backup, keep track of the latest processed change ID (via xref:procedures/index.adoc#current[`db.cdc.current()`]) and use it to query for changes after importing the next backup.
