[role=enterprise-edition]
[[change-data-capture]]
ifndef::backend-pdf[]

= Introduction

endif::[]
ifdef::backend-pdf[]

= Change Data Capture

== Introduction

endif::[]

Change Data Capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up-to-date and accurate.
With CDC, you can identify and respond to changes (create, update, and delete) on your graph entities (nodes and relationships) as they happen, and integrate these changes into other systems and applications.

The CDC feature is straightforward to set up and use and allows you to quickly and efficiently capture and replicate changes to your data without disruptions to your workflow.

The documentation guides you through the process of setting up CDC, configuring it to capture the changes, and querying those changes for further processing, such as replicating to another system.
It also contains best practices and troubleshooting tips to ensure that your CDC implementation runs smoothly.

== Availability

The CDC feature is available as a public beta with Neo4j Enterprise Edition 5.13 and AuraDB Enterprise.

=== Neo4j 5.13
As of Neo4j 5.13 the cdc feature has the following known issues.

==== Entity keys
Neo4j permits multiple `KEY` constraints on any given label.
Change data capture does not distinguish between separate key entries for the same label and merges the properties from each key constraint into one map.
This may lead to unexpected behaviour around selecting changes by node or relationship key.

There will likely be API changes to resolve this issue during the beta phase.

==== Selector behaviour
In Neo4j 5.13 change selectors are evaluated against the state of the changed entity as it was before the change was applied.
This may lead to unexpected behaviour when selecting changes based on properties that have changed.

As an example, the following change would not be returned when using the selector `{select:n, labels:[NEW_LABEL]}`

`MATCH (n:OLD_LABEL) SET n:NEW_LABEL REMOVE n:OLD_LABEL`

An update, to instead evaluate the selector against a combination of `before` and `after` state, will be considered during the beta phase.
