[role=enterprise-edition]
[[change-data-capture]]
= Introduction

Change data capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up-to-date and accurate.
With CDC, you can identify and respond to changes (create, update, and delete) on your graph entities (nodes and relationships) as they happen, and integrate these changes into other systems and applications.

Our CDC feature is easy to set up and use, allowing you to quickly and efficiently capture and replicate changes to your data without disrupting your workflow.
With its flexible configuration options, you can choose to capture changes on a per-database basis, and query changes with advanced filtering support to fit your needs.

In this documentation, we will guide you through the process of setting up CDC, configuring it to capture the changes, and querying those changes to further processing, such as replicating to another system.
We will also provide you with best practices and troubleshooting tips to ensure that your CDC implementation runs smoothly.

== Known Limitations

* CDC in a cluster environment might raise errors when a CDC query is completed in one cluster member and the next query is executed in another member that has just completed a store copy.
Retrying the query on a different member might help resolve the error.
_**There is already work going on to have a consistent view of transaction logs on all cluster members that host the database in question, but this view will only be limited to cover the period defined by `db.tx_log.rotation.retention_policy` setting.**_