// suppress inspection "JsonStandardCompliance" for whole file
// ^ Avoid errors on "// <1>" annotations in json source blocks

// Creating a cdc enabled build:
// Add CDC dependency to private/enterprise/neo4j-enterprise/pom.xml

[role=enterprise-edition]
[[change-data-capture]]
= Introduction

Change data capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up-to-date and accurate.
With CDC, you can identify and respond to changes (create, update, and delete) on your graph entities (nodes and relationships) as they happen, and integrate these changes into other systems and applications.

Our CDC feature is easy to set up and use, allowing you to quickly and efficiently capture and replicate changes to your data without disrupting your workflow.
With its flexible configuration options, you can choose to capture changes on a per-database basis, and query changes with advanced filtering support to fit your needs.

In this documentation, we will guide you through the process of setting up CDC, configuring it to capture the changes, and querying those changes to further processing, such as replicating to another system.
We will also provide you with best practices and troubleshooting tips to ensure that your CDC implementation runs smoothly.

====
TODO examples are similar to the movie graph, but not actually following the movie graph. See if northwind is complicated enough or if we should go with our own.
====

====
*TODO put these topics/stuff somewhere:*

- For create events `event.state.before` is null
- For delete events `event.state.after` is null
- For update events neither is null, they might be empty maps for diff mode
- Clustering support
- Guarantee of changes in clustering

*Current docs todos*



- example cdc application
- add return values to applicable cypher statements, such as: https://neo4j.com/docs/operations-manual/current/manage-databases/queries/#manage-databases-queries-show-database



*Scenarios?*

- Start/Stop database
- Leader switch
- Enable/Disable/Change enrichment mode
* DIFF -> FULL -> DIFF is silent, but causes different output?

*TODO finishing touches:*

- Make sure links work and make sense (don't put a link from one section to the one right below...)
- double check "earliest" syntax in examples, is "0" always valid as "earliest"
- Delete this TODO list...
====