ifndef::backend-pdf[]

= Introduction

endif::[]
ifdef::backend-pdf[]

= Change Data Capture

== Introduction

endif::[]

Change Data Capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up to date with Neo4j. With CDC, you can identify and respond to changes (create, update, and delete) on nodes and relationships as they happen, and integrate these changes into other systems and applications.

The documentation guides you through the process of setting up CDC, configuring it to capture the changes, and querying those changes for further processing, such as replicating to another system.

[NOTE]
====
Certain metadata such as creation date, creating user and internal IDs cannot be replicated into another Neo4j database using CDC.
Hosting Neo4j in a link:{neo4j-docs-base-uri}/operations-manual/current/clustering/introduction/[cluster] or creating offline copies by leveraging link:{neo4j-docs-base-uri}/operations-manual/current/backup-restore/[backups] may be more appropriate when an exact copy is necessary.
====