ifndef::backend-pdf[]

= Introduction

endif::[]
ifdef::backend-pdf[]

= Change Data Capture

== Introduction

endif::[]

Change Data Capture (CDC) allows you to capture and track changes to your database in real-time, enabling you to keep your other data sources up to date with Neo4j. With CDC, you can identify and respond to changes (create, update, and delete) on nodes and relationships as they happen, and integrate these changes into other systems and applications.

The documentation guides you through the process of setting up CDC, configuring it to capture the changes, and querying those changes for further processing, such as replicating to another system.

[NOTE]
====
CDC is not the right tool to create an _exact_ copy of a Neo4j database, as certain entities would not be replicated (examples of such metadata are: creation date, creating user, internal IDs).
Hosting Neo4j in a link:{neo4j-docs-base-uri}/operations-manual/current/clustering/introduction/[cluster] or creating offline copies through link:{neo4j-docs-base-uri}/operations-manual/current/backup-restore/[backups] is more appropriate when an exact copy is necessary.
====
