= CDC procedures

[[change-data-capture-querying-changes]]
== Querying changes
The procedure `cdc.query(from, selectors)` is used to query the database for changes.
Once all changes have been streamed the query will terminate.
Each record contains an `id` field, which can be used as `from` in a subsequent query, in order to continue streaming from that point.
The `from` field is exclusive and will not include the already seen record a second time.
Selectors can be used to filter the output, see xref:selectors.adoc[selectors] for details.

[source, cypher]
----
CALL cdc.query("A-I5vnbH6EPYqgNWfeWS9CYAAAAAAAAABQAAAAAAAAAA")
CALL cdc.query("A-I5vnbH6EPYqgNWfeWS9CYAAAAAAAAABQAAAAAAAAAA", {select:"n"})
----

The output from `cdc.query` is described in xref:output-schema.adoc[].

== Getting the earliest change
The procedure `cdc.earliest` is used to get a `from` value for the earliest available change.
[source, cypher]
----
CALL cdc.earliest
----

The following affect what the earliest value is:

* Transaction log enrichment has been turned off
====
TODO Do we need to be more explicit about this? Maybe some sentence in the enrichment mode section that turning enrichment OFF voids all previous data?
====
* Transaction log rotation
====
TODO are there other things that affect the earliest value?
====

=== Getting the current change
The procedure `cdc.current` returns the `id` from the latest entry in the transaction log.
This value may be used to query changes from "now".
[source, cypher]
----
CALL cdc.current
----
