// suppress inspection "JsonStandardCompliance" for whole file
// ^ Avoid errors on "// <1>" annotations in json source blocks
[[cdc-selectors]]
= Selectors
[[change-data-capture-selectors]]
== Selectors
Change data capture procedures support filtering their output using selectors.

The following cypher will only return changes where the property "name" has changed on nodes.
[source, cypher]
----
CALL cdc.query("0", [{select:"n", changesTo:["name"]}])
----

=== Combining selectors
The more specific a selector is, the fewer changes will be returned.
Specifying both "name" and "surname" for example, will only return changes where both `name` *and* `surname` properties are changed.

[source, cypher]
----
CALL cdc.query("0", [{select:"n", changesTo:["name", "surname"]}])
----

In order to extract changes for either `name` *or* `surname` properties, two separate selectors have to be specified:

[source, cypher]
----
CALL cdc.query("0", [
    {select:"n", changesTo:["name"]}
    {select:"n", changesTo:["surname"]}
])
----


=== Examples
// ENTITY UNSPECIFIC
Changes can be filtered to only return creates, updates or deletes, regardless of whether the effected entity is a node or a relationship:

[source, cypher]
----
CALL cdc.query("0", [{select:"e", operation:"c"}])
CALL cdc.query("0", [{select:"e", operation:"u"}])
CALL cdc.query("0", [{select:"e", operation:"d"}])
----

Changes can be filtered to only include those where a certain property is changed.

[source, cypher]
----
CALL cdc.query("0", [{select:"e", changesTo:["name"]}])
----

// NODE/RELATIONSHIP needs to be specified
Changes can be filtered to a specific element ID.

[source, cypher]
----
CALL cdc.query("0", [{select:"n", elementId:"4:e239be76-c7e8-43d8-aa03-567de592f426:0"}])
CALL cdc.query("0", [{select:"r", elementId:"5:e239be76-c7e8-43d8-aa03-567de592f426:0"}])
----

// NODE selectors
Node changes can be filtered to specific keys. The provided key needs to fully match to a corresponding node key or property existence and uniqueness constraints on the node.

[source, cypher]
----
CALL cdc.query("0", [{select:"n", key:{name:"Kevin", surname:"Bacon"}}])
----

[NOTE]
====
If the constraints are added after a node has created, the change event will not be updated retroactively.
====

Node changes can be filtered to specific labels.

[source, cypher]
----
CALL cdc.query("0", [{select:"n", labels:["ACTOR", "DIRECTOR"]}])
----

[NOTE]
====
The query above will only return changes on nodes that have *both* labels.
In order to get changes on nodes with either label, two separate selectors have to be specified.

[source, cypher]
----
CALL cdc.query("0", [{select:"n", labels:["ACTOR"]}, {select:"n", labels:["DIRECTOR"]}])
----
====

// RELATIONSHIP selectors
Relationship changes can be filtered to a specific type.

[source, cypher]
----
CALL cdc.query("0", [{select:"r", type:"ACTED_IN"}])
----

Relationship changes can be selected based on their start and end nodes.

[source, cypher]
----
CALL cdc.query("0", [{
    select:"r",
    start:{labels:["ACTOR"]},
    end:{key:{title:"Apollo 13"}}
}])
----


=== Schema
==== Entity selector schema
[source, json]
----
{
  "select": "e", // <1>
  "operation": "c", // <2>
  "changesTo": ["name", "title"] // <3>
}
----
All fields except for `select` are optional.

<1> Select changes on all entities. Other valid values are `"n"` for node changes and `"r"` for relationship changes.
<2> Select changes which are creating entities. Other valid values are `"u"` for entity updates and `"d"` for entity deletions.
<3> Select changes which affect all specified properties.

==== Node selector schema
[source, json]
----
{
  "select": "n", // <1>
  "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <2>
  "key": { // <3>
    "property": "value",
    "otherProperty": "value"
  },
  "labels": ["Person", "Actor"], // <4>
  "operation": "c", // <5>
  "changesTo": ["name", "lastName"] // <6>
}
----
All fields except for `select` are optional.

<1> Select changes on nodes. Other valid values are `"e"` for all entity types and `"r"` for relationship changes.
<2> Select changes on the node with this elementId.
<3> Select changes on nodes with matching key properties. Key matching is only possible when there is a defined node key or property existence and uniqueness constraints defined on one of the labels set on the affected node, see xref:constraints.adoc[] for details.
<4> Select changes on nodes which have all specified labels.
<5> Select changes which are creating nodes. Other valid values are `"u"` for node updates and `"d"` for node deletions.
<6> Select changes which affect all specified properties.

==== Relationship selector schema
[source, json]
----
{
  "select": "r", // <1>
  "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <2>
  "type": "ACTED_IN", // <3>
  "start": { // <4>
    "select": "n", // <5>
    "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <6>
    "key": { // <7>
      "userId": "1001",
      "name": "John"
    },
    "labels": ["Person", "Actor"] // <8>
  },
  "end":{ // <9>
    "select": "n",
    "elementId": "5:b7e35973-0aff-42fa-873b-5de31878ab4a:3",
    "key": {
      "title": "Matrix"
    },
    "labels": ["Movie"]
  },
  "operation": "c", // <10>
  "changesTo": ["name", "lastName"] // <11>
}
----
All fields except for `select` are optional.

<1> Select changes on nodes, other valid values are `"e"` for all entity types and `"n"` for node changes.
<2> Select changes on the relationship with this elementId.
<3> Select changes on relationships with this type.
<4> Select changes on relationships with a start node matching this node selector. Note that `operation` and `changesTo` are not valid inside these node selectors.
<5> Optionally specify that this is a node selector, specifying `"r"` or `"e"` here will cause an error.
<6> Select relationships where the start node has this elementId.
<7> Select relationships where the start node has these key properties. Key matching is only possible when there is a defined relationship key or property existence and uniqueness constraints defined on the relationship type, see xref:constraints.adoc[] for details.
<8> Select relationships where the start node has these labels.
<9> Same schema as `start`.
<10> Select changes which are creating relationships. Other valid values are `"u"` for updates and `"d"` for deletes.
<11> Select changes where all specified properties are affected.
