// suppress inspection "JsonStandardCompliance" for whole file
// ^ Avoid errors on "// <1>" annotations in json source blocks
= Schema

This section introduces the complete schema for selectors.

== Schema for selecting both nodes and relationships
[source, json]
----
{
  "select": "e", // <1>
  "operation": "c", // <2>
  "changesTo": ["name", "title"] // <3>
}
----
All fields except for `select` are optional.

<1> Select changes on all entities. Other valid values are `"n"` for node changes and `"r"` for relationship changes.
<2> Select changes which are creating entities. Other valid values are `"u"` for entity updates and `"d"` for entity deletions.
<3> Select changes which affect all specified properties.

== Schema for selecting nodes
[source, json]
----
{
  "select": "n", // <1>
  "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <2>
  "key": { // <3>
    "property": "value",
    "otherProperty": "value"
  },
  "labels": ["Person", "Actor"], // <4>
  "operation": "c", // <5>
  "changesTo": ["name", "lastName"] // <6>
}
----
All fields except for `select` are optional.

<1> Select changes on nodes. Other valid values are `"e"` for all entity types and `"r"` for relationship changes.
<2> Select changes on the node with this elementId.
<3> Select changes on nodes with matching key properties. Key matching is only possible when there is a defined node key or property existence and uniqueness constraints defined on one of the labels set on the affected node, see xref:getting-started/constraints.adoc[] for details.
<4> Select changes on nodes which have all specified labels.
<5> Select changes which are creating nodes. Other valid values are `"u"` for node updates and `"d"` for node deletions.
<6> Select changes which affect all specified properties.

== Schema for selecting relationships
[source, json]
----
{
  "select": "r", // <1>
  "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <2>
  "type": "ACTED_IN", // <3>
  "start": { // <4>
    "select": "n", // <5>
    "elementId": "4:b7e35973-0aff-42fa-873b-5de31868cb4a:1", // <6>
    "key": { // <7>
      "userId": "1001",
      "name": "John"
    },
    "labels": ["Person", "Actor"] // <8>
  },
  "end":{ // <9>
    "select": "n",
    "elementId": "5:b7e35973-0aff-42fa-873b-5de31878ab4a:3",
    "key": {
      "title": "Matrix"
    },
    "labels": ["Movie"]
  },
  "operation": "c", // <10>
  "changesTo": ["name", "lastName"] // <11>
}
----
All fields except for `select` are optional.

<1> Select changes on nodes, other valid values are `"e"` for all entity types and `"n"` for node changes.
<2> Select changes on the relationship with this elementId.
<3> Select changes on relationships with this type.
<4> Select changes on relationships with a start node matching this node selector. Note that `operation` and `changesTo` are not valid inside these node selectors.
<5> Optionally specify that this is a node selector, specifying `"r"` or `"e"` here will cause an error.
<6> Select relationships where the start node has this elementId.
<7> Select relationships where the start node has these key properties. Key matching is only possible when there is a defined relationship key or property existence and uniqueness constraints defined on the relationship type, see xref:getting-started/constraints.adoc[] for details.
<8> Select relationships where the start node has these labels.
<9> Same schema as `start`.
<10> Select changes which are creating relationships. Other valid values are `"u"` for updates and `"d"` for deletes.
<11> Select changes where all specified properties are affected.
