= Enable CDC on Aura instances (cloud)


include::partial$get-started.adoc[tags=intro]


[[set-enrichment-mode]]
== Set the enrichment mode

In the Aura Console, click on the three dots on an instance card, then select “Edit CDC Enrichment Mode”.
By default, the CDC enrichment mode is set to OFF for all new, cloned, and paused instances, and also for instances that have been restored from a snapshot. 
Only admins can change the CDC enrichment mode. 
If CDC enrichment mode is DIFF or FULL, we recommend not pausing the database.
[IMPORTANT]
====
Modifying enrichment mode from `DIFF` to `FULL` or viceversa immediately changes the  xref:procedures/output-schema.adoc[structure of captured changes].
Your CDC application must be able to deal with the different format.
====

[WARNING]
====
Disabling enrichment immediately breaks the continuity of change events.
**Change identifiers generated before disabling can no longer be used and, even if enrichment is re-enabled, the previously-generated change identifiers remain invalid.**
Disabling and then re-enabling CDC is equivalent to enabling it for the first time: there is no memory of previous changes.
====

== Points to consider


[[log-retention]]
=== Transaction log retention

What's the default log retention period on aura instances?


[[pause-resume]]
=== Pause/Resume instances

Pause-resume will automatically disable cdc, re enabling invalidates the cursor.
