= Enable CDC on Aura instances (cloud)


include::partial$get-started.adoc[tags=intro]


[[set-enrichment-mode]]
== Set the enrichment mode

=== Create a database with log enrichment enabled


=== Modify a database's log enrichment mode


[IMPORTANT]
====
Modifying enrichment mode from `DIFF` to `FULL` or viceversa immediately changes the  xref:procedures/output-schema.adoc[structure of captured changes].
Your CDC application must be able to deal with the different format.
====

=== Disable log enrichment


[WARNING]
====
Disabling enrichment immediately breaks the continuity of change events.
**Change identifiers generated before disabling can no longer be used and, even if enrichment is re-enabled, the previously-generated change identifiers remain invalid.**
Disabling and then re-enabling CDC is equivalent to enabling it for the first time: there is no memory of previous changes.
====

== Points to consider

[[security]]
=== Security

USer access


[[log-retention]]
=== Transaction log retention

What's the default log retention period on aura instances?


=== Pause/Resume instances
